### ISSUE TITLE
Setup Angular project

### ISSUE THREAD

**Issue by durixx** [durixx/library_frontend#1]
Setup new Angular project 

the project should be empty for now
except change home page to display only hello world

**Comment by serox2255** [comment]
done
24.10 15min

**Comment by durixx** [comment]
missing pull request

**Comment by serox2255** [comment]
done
24.10 30min

**Comment by durixx** [comment]
Code review NOT OK

**Comment by serox2255** [comment]
done

**Comment by serox2255** [comment]
25.10 
15min
